### ISSUE TITLE
Please clarify image size limitations

### ISSUE THREAD

**Issue by tokee** [Det-Kongelige-Bibliotek/access-digital-objects#2]
The JSON at https://github.com/Det-Kongelige-Bibliotek/access-digital-objects/blob/master/image-delivery.md shows that the sample image is `2940x2212` pixels, with sizes including up to `1470x1106` pixels. The sample request for the image itself uses `2000` pixels as width.

Where does the `2000` number come from? Since incrementing with just a single pixel to `2001` results in the error message _"Requested width is above server limit 2000 px"_, it indicates that there is a conscious decision to limit maximum image size. This should be clearly stated on the web page.

**Comment by siglun** [comment]
I'll revise this part when we've released our new IIP image config.

**Comment by siglun** [comment]
The new resolution is now limited to 8000 x 8000px which is beyond  most of our images.

**Comment by tokee** [comment]
Thank you. This works so much better for the maps!
