### ISSUE TITLE
Please raise the maximum image size on the image server

### ISSUE THREAD

**Issue by tokee** [Det-Kongelige-Bibliotek/access-digital-objects#3]
The images from the Atlas and Maps collections seems to be scanned with an appropriate pixel count for the material, such as http://kb-images.kb.dk/online_master_arkiv_6/non-archival/Maps/KORTSA/ATLAS_MAJOR/Kbk2_2_63/Kbk2_2_63_009/info.json that is `9019x7939` pixels. Unfortunately the servers image width limit of `2000` pixels (see issue #2) means that the map cannot be retrieved at a size that makes the map text legible.

Hopefully the image servers limits can be raised to allow serving the images at full resolution. Alternatively a direct download link to the raw scanned image would be nice.

**Comment by siglun** [comment]
We are about to do that; it's in the pipeline but I cannot give you the exact date.

**Comment by siglun** [comment]
done
