### ISSUE TITLE
Browsing beyond 400 collection items seems to be disabled

### ISSUE THREAD

**Issue by tokee** [Det-Kongelige-Bibliotek/access-digital-objects#4]
I am trying to bulk-process collections for a visualization experiment and am using the API described on https://github.com/Det-Kongelige-Bibliotek/access-digital-objects/blob/master/cop-backend.md

When requesting page 1-8 with calls such as http://www.kb.dk/cop/syndication/images/billed/2010/okt/billeder/da/?itemsPerPage=50&orderBy=notBefore&subject=209&page=8 the results are as expected. However, when requesting page 9 and beyond, such as http://www.kb.dk/cop/syndication/images/billed/2010/okt/billeder/da/?itemsPerPage=50&orderBy=notBefore&subject=209&page=9 the result is the same as page 8, indicating a silent limit on paging. Switching to `itemsPerPage=40` resulted in repetition of lookup-result from page 10 and forward.

I realize there can be technical reasons for discouraging deep-paging. It is somehow possible to do so anyway or alternatively access the full list of elements in a given collection somewhere else?

**Comment by tokee** [comment]
Related observation: The GUI for searching collections allows for (at least) paging through 6000 results: http://www.kb.dk/maps/kortsa/2012/jul/kortatlas/subject206/da/?searchAcrossEditions=false&query=*%3A*&orderBy=&title=&creator=&person=&location=&notBefore=&notAfter=&page=100 and http://www.kb.dk/maps/kortsa/2012/jul/kortatlas/subject206/da/?searchAcrossEditions=false&query=*%3A*&orderBy=&title=&creator=&person=&location=&notBefore=&notAfter=&page=101 present different images.

**Comment by siglun** [comment]
Sounds very much like a bug, but I honestly don't know.

We have a revised backend ready for test and deploy which is based on SOLR for search (still using Oracle for storage) which will change things. Don't want to work with this on the current oracle/rdbms based retrieval system.

Otherwise, thanks a lot for input!

**Comment by tokee** [comment]
Fair enough. Solr is not too happy about millions-deep paging without using cursors, but a few hundred thousand records it not a problem.
